import { resolveApiErrorMessage } from "./apiError";

export const FINANCE_ERROR_CODES = {
    finance_expense_accounts_required: "finance.error_expense_accounts_required",
    finance_cash_account_required: "finance.error_cash_account_required",
    finance_income_accounts_required: "finance.error_income_accounts_required",
    reconciliation_match_fields_required: "finance.error_reconciliation_match_fields_required",
    cash_account_not_found: "finance.error_cash_account_not_found",
    cash_account_chart_account_invalid: "finance.error_cash_chart_account_invalid",
    cash_account_name_required: "finance.error_cash_name_required",
    cash_account_type_invalid: "finance.error_cash_type_invalid",
    cash_account_location_required: "finance.error_cash_location_required",
    reconciliation_entries_required: "finance.error_reconciliation_entries_required",
    reconciliation_import_limit: "finance.error_reconciliation_import_limit",
    reconciliation_entry_invalid: "finance.error_reconciliation_entry_invalid",
    reconciliation_entry_duplicate: "finance.error_reconciliation_entry_duplicate",
    reconciliation_status_invalid: "finance.error_reconciliation_status_invalid",
    reconciliation_start_date_invalid: "finance.error_reconciliation_start_date_invalid",
    reconciliation_end_date_invalid: "finance.error_reconciliation_end_date_invalid",
    reconciliation_entry_not_found: "finance.error_reconciliation_entry_not_found",
    reconciliation_movement_not_found: "finance.error_reconciliation_movement_not_found",
    reconciliation_entry_already_matched: "finance.error_reconciliation_entry_already_matched",
    reconciliation_movement_already_matched: "finance.error_reconciliation_movement_already_matched",
    reconciliation_amount_mismatch: "finance.error_reconciliation_amount_mismatch",
    reconciliation_concurrent_change: "finance.error_reconciliation_concurrent_change",
    receivable_due_date_invalid: "finance.error_receivable_due_date_invalid",
    receivable_order_not_found: "finance.error_receivable_order_not_found",
    payable_due_date_invalid: "finance.error_payable_due_date_invalid",
    payable_purchase_not_found: "finance.error_payable_purchase_not_found",
    cash_adjustment_accounts_required: "finance.error_cash_adjustment_accounts_required",
    cash_adjustment_amount_invalid: "finance.error_cash_adjustment_amount_invalid",
    cash_adjustment_reason_required: "finance.error_cash_adjustment_reason_required",
    cash_adjustment_date_invalid: "finance.error_cash_adjustment_date_invalid",
    cash_adjustment_cash_account_not_found: "finance.error_cash_adjustment_cash_account_not_found",
    cash_adjustment_counterpart_not_found: "finance.error_cash_adjustment_counterpart_not_found",
    cash_adjustment_negative_balance: "finance.error_cash_adjustment_negative_balance",
    cash_adjustment_same_counterpart: "finance.error_cash_adjustment_same_counterpart",
    cash_transfer_accounts_required: "finance.error_cash_transfer_accounts_required",
    cash_transfer_same_account: "finance.error_cash_transfer_same_account",
    cash_transfer_amount_invalid: "finance.error_cash_transfer_amount_invalid",
    cash_transfer_date_invalid: "finance.error_cash_transfer_date_invalid",
    cash_transfer_account_not_found: "finance.error_cash_transfer_account_not_found",
    cash_transfer_insufficient_funds: "finance.error_cash_transfer_insufficient_funds",
    manual_income_amount_invalid: "finance.error_manual_income_amount_invalid",
    manual_income_date_invalid: "finance.error_manual_income_date_invalid",
    manual_income_revenue_account_not_found: "finance.error_manual_income_revenue_account_not_found",
    manual_income_cash_account_not_found: "finance.error_manual_income_cash_account_not_found",
    manual_income_statement_entry_unavailable: "finance.error_manual_income_statement_entry_unavailable",
    manual_income_statement_amount_mismatch: "finance.error_manual_income_statement_amount_mismatch",
    manual_income_statement_concurrent_change: "finance.error_statement_concurrent_change",
    manual_expense_amount_invalid: "finance.error_manual_expense_amount_invalid",
    manual_expense_date_invalid: "finance.error_manual_expense_date_invalid",
    manual_expense_expense_account_not_found: "finance.error_manual_expense_expense_account_not_found",
    manual_expense_cash_account_not_found: "finance.error_manual_expense_cash_account_not_found",
    manual_expense_statement_entry_unavailable: "finance.error_manual_expense_statement_entry_unavailable",
    manual_expense_statement_amount_mismatch: "finance.error_manual_expense_statement_amount_mismatch",
    manual_expense_insufficient_funds: "finance.error_manual_expense_insufficient_funds",
    manual_expense_statement_concurrent_change: "finance.error_statement_concurrent_change",
    order_payment_order_not_found: "finance.error_order_payment_order_not_found",
    order_payment_amount_invalid: "finance.error_order_payment_amount_invalid",
    order_payment_order_cancelled: "finance.error_order_payment_order_cancelled",
    order_payment_cash_account_not_found: "finance.error_order_payment_cash_account_not_found",
    order_payment_exceeds_balance: "finance.error_order_payment_exceeds_balance",
    order_payment_concurrent_change: "finance.error_payment_concurrent_change",
    purchase_payment_purchase_not_found: "finance.error_purchase_payment_purchase_not_found",
    purchase_payment_amount_invalid: "finance.error_purchase_payment_amount_invalid",
    purchase_payment_cash_account_not_found: "finance.error_purchase_payment_cash_account_not_found",
    purchase_payment_exceeds_balance: "finance.error_purchase_payment_exceeds_balance",
    purchase_payment_insufficient_funds: "finance.error_purchase_payment_insufficient_funds",
    purchase_payment_concurrent_change: "finance.error_payment_concurrent_change",
};

export const financeErrorMessage = (error, t, fallbackKey = "finance.failed") =>
    resolveApiErrorMessage(error, t, FINANCE_ERROR_CODES, fallbackKey);
